import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "@next/font/google";
import "./globals.css"; // Assicurati di avere uno stile globale

// Carica il font
const roboto = Roboto({
  subsets: ["latin"], // Specifica i subset che vuoi usare
  weight: ["400", "700"], // Pesi disponibili
  variable: "--font-roboto", // Variabile CSS per il font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>{children}</body>
    </html>
  );
}
